apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${project.artifactId}
  namespace: suqi-center
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${project.artifactId}
  template:
    metadata:
      labels:
        app: ${project.artifactId}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: ${project.artifactId}
          image: ${registry}/suqi-center/${project.artifactId}:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 20000
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "0.9"
              memory: 1Gi
          volumeMounts:
            - mountPath: /data/usr/local/suqi-center/logs/
              name: fastcloud-logs
          env:
            - name: TZ
              value: Asia/Shanghai  # 设置系统时间
            - name: JAVA_TOOL_OPTIONS
              value: -Dspring.profiles.active=logstash -Dspring.cloud.nacos.config.serverAddr=192.168.22.210:31010  -Dspring.cloud.nacos.discovery.serverAddr=192.168.22.210:31010
      volumes:
        - name: fastcloud-logs
          hostPath:
            path: /data/usr/local/suqi-center/logs/
---
apiVersion: v1
kind: Service
metadata:
  name: ${project.artifactId}-service
  namespace: suqi-center
  labels:
    app: ${project.artifactId}
spec:
  type: NodePort
  selector:
    app: ${project.artifactId}
  ports:
    - name: ${project.artifactId}
      protocol: TCP
      port: 20000
      targetPort: 20000
      nodePort: 30103